FROM alarsencoh/ubuntu-16.04_bootstrap@sha256:4d91005b16e8c4cd4dc44a5d7332a5b8ad12d65e764231343df4ed9bb55d7d1c

#FROM alarsencoh/ubuntu-16.04_base@sha256:a4fc0c40360ff2224db3a483e5d80e9164fe3fdce2a8439d2686270643974632 AS build
#
#RUN apt update -y && \
#    apt install -y apt-utils && \
#    apt autoremove -y && \
#    apt clean
#
#ENV DEBIAN_FRONTEND noninteractive
#
#RUN apt update -y && \
#    apt install -y \
#     bison \
#     build-essential \
#     ccache \
#     cmake \
#     file \
#     gawk \
#     gettext \
#     git \
#     linux-headers-generic \
#     m4 \
#     meson \
#     ninja-build \
#     pkg-config \
#     python3-setuptools \
#     subversion \
#     texinfo \
#     wget \
#     && \
#    apt autoremove -y && \
#    apt clean

##RUN update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.lld-10" 20 && \
##    update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.bfd" 10 && \
##    update-alternatives --config ld

